UserInfo:
  account: 11111
  username: "张三"
  age: 20
  sex: true
  accountAndPaswd:
    11111: 123456
  list:
    - "李四"
    - "王五"
    - "赵六"

spring:
  profiles:
    active: dev
---
service:
  port: 8081
spring:
  profiles:dev

---
server:
  port: 8082